name: Release

on:
  # Run when pushing a tag that matches the pattern.
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          # - ios-latest
        # dotnet-version: [ '3.1.x', '6.0.x' ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK # ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          # dotnet-version: ${{ matrix.dotnet-version }}
          dotnet-version: '6.0.x'
        # TODO: This should be cached
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
      - name: Check Files
        run: |
          ls
          ls ./ConsoleApp/bin/Release/net6.0/*
      - name: Upload Artefact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}
          path: ./ConsoleApp/bin/Release/net6.0/*

  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # download all artefacts
      - name: Prepare Artefacts
        uses: actions/download-artifact@v3
      - name: Display artefact structure
        run: ls -R
      # upload to release
      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: |
            README.md
            LICENSE-APACHE
            LICENSE-MIT
